version: '3'
services:
  spring-docker-sample:
    container_name: spring-docker-sample
    image: spring-docker-sample:latest
    build: .
    ports:
      - "8080:8080"
    networks:
      - spring-docker-sample-network
    environment:
      - "JAVA_OPTS=-server -verbose:gc -Xmx1024m -Xms1024m -XX:MetaspaceSize=150m -XX:MaxMetaspaceSize=256m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=45 -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -XX:+UseContainerSupport -Dfile.encoding=UTF-8"
networks:
  spring-docker-sample-network:
